version: '3.7'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
          #init: true
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_HOST
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    ports:
      - 9000
      - 3306
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
        #init: true
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
      - 9000
    restart: on-failure
    depends_on:
      - wordpress
volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/DB
      o: bind

  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/WordPress
      o: bind

networks:
  inception:
    driver: bridge

